# Generated by Django 5.1.7 on 2025-03-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0003_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
    ]
